In [111]:
from matplotlib import axes as ax
import numpy as np
import matplotlib.pyplot as plt


def lesaurslit():
    file = "https://cs.hi.is/python/kosningar-2021.txt"
    A = np.loadtxt(file, dtype=str, skiprows=1).T
    Listi = A[0].tolist()
    Atkvaedi = A[1].astype(int)
    Thingsaeti = A[2].astype(int)
    return Listi, Atkvaedi, Thingsaeti

(listi, atkvæði, þingsæti) = lesaurslit()

def flokkslitir():
    file = "https://cs.hi.is/python/flokkslitir.txt"
    (stafur,litur,flokkur) = np.loadtxt(file, dtype=str, comments=None, delimiter=",", skiprows=1).T
    return stafur, litur, flokkur

(stafur, litur, nafn) = flokkslitir()

litatafla = dict(zip(stafur,litur))


nafnatafla = dict(zip(stafur,nafn))


def litirognofn(x,y,z,q):
    litir = dict(zip(x,y))
    nöfn = dict(zip(z,q))
    return (litir, nöfn)

(litir,nöfn) = litirognofn(listi,stafur,litur,nafn)


litir = [litatafla[st] for st in listi]
nöfn = [nafnatafla[arr] for arr in listi]


n = len(listi)
x = range(n)

def addlabels(x,y):
    for i in range(len(x)):
        plt.text(i, y[i], y[i], ha = 'center')

def prósentuformat(ás):
    plt.figure(figsize=(12,5))
    plt.xticks(x, nöfn, rotation="vertical")
    """merkir ás ("x" eða "y") með prósentum"""
    from matplotlib.ticker import FuncFormatter
    ásar = plt.gca() # get current axes
    xy = ásar.xaxis if ás=="x" else ásar.yaxis
    xy.set_major_formatter(FuncFormatter('{0:.0%}'.format))
    ax = plt.bar(x, hlutfall, color=litir , linewidth=0.6, zorder=3)
    addlabels(nöfn, new_lst)
    plt.grid(True, axis='y')
    plt.ylabel('Hlutfall atkvæða')
    plt.title('Úrslit alþingiskosninga 2021 og úthlutuð þingsæti')
    plt.show()

hlutfall = atkvæði/sum(atkvæði)
prósentuformat(x)
new_lst = [round(i*100,1) for i in hlutfall]



ConversionError: Failed to convert value(s) to axis units: '17.3%'

<Figure size 1200x500 with 1 Axes>

In [64]:
import numpy as np, numpy.linalg as la

a = np.array([3,2,8])
b = np.array([2,0,1])
c = np.array([-2,1,5])
A = np.array([[2,4,7], [3,4,8], [4,6,9]])
B = np.array([[5,5,5], [6,6,6], [7,8,9]])

print(a*b-((c*(B*b))/3* abs(abs(c))))
print(2*(A.T +B**2)*(a-2*b))
print(la.det(A))
print(la.inv(A))
x = la.solve(A, b)
print(x)




[[ 19.33333333   0.         -33.66666667]
 [ 22.           0.         -42.        ]
 [ 24.66666667   0.         -67.        ]]
[[ -54  112  348]
 [ -80  160  504]
 [-112  288 1080]]
10.000000000000002
[[-1.2  0.6  0.4]
 [ 0.5 -1.   0.5]
 [ 0.2  0.4 -0.4]]
[-2.   1.5  0. ]


In [71]:
# for i in range(0,n-1):
#     j=0
#     (i-j)*x[j]+x[i]
#     print(x)
# n=4

def leysa(n):
   A = np.zeros((n,n))
   b = np.zeros(n)
   for i in range(n-1):
      A[i,(i,i+1)] = [-1, 2]  # setjum tvö stök í einu
   for j in range(n):
      A[n-1,j] = 1            # ásar í neðstu línu
   b[n-1] = 3*n
   x = la.solve(A, b)
   return x
leysa(2)


array([4., 2.])